name: test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev-v4
  pull_request:
    branches:
      - master
      - dev-v4

jobs:
  test:
    name: test (${{ matrix.module }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        module:
          - .
          - examples/getting-started
          - examples/helloworld
          - examples/login-form
          - examples/ssr
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ matrix.module }}/go.mod
          cache: true
          cache-dependency-path: ${{ matrix.module }}/go.sum

      - name: Test
        working-directory: ${{ matrix.module }}
        run: go test -race -timeout 30m ./...
